@startuml BancoDeSangre
class BancoDeSangre {
    - donantes : Donante[]
    - direccion : String
    - personal : Personal[]
    + BuscarPorCI(CI : String) : Donante
    + ListarPorMayorCantidad(cantidad : int) : Donante[]
    + BuscarCIDonanteOPos(mes : int) : String
    + BuscarVolumenTotalDonanteOPos() : float
    + OrdenarPorNombre() : Donante[]
    + OrdenarPorGrupoSanguineo() : Donante[]
    + AddDonante(donante : Donante) : void
    + EliminarDonante(donante : Donante) : void
    + ModificarDonante(donante : Donante) : void
    + AddDonacion(donante : Donante, Donacion : Donacion) : void
    + EliminarDonacion(donante : Donante, Donacion : Donacion) : void
    + ModificarDonacion(donante : Donante, Donacion : Donacion) : void
    + AddPersonal(personal : Personal) : void
    + EliminarPersonal(personal : Personal) : void
    + ModificarPersonal(personal : Personal) : void
}

class Donante{
    - CI : String
    - nombre_completo : String
    - grupo_sanguineo : String
    - factor_rh : String
    - direccion : String
    - observaciones : String
    - donaciones : Donacion[]

    + Donante(CI : String, nombre_completo : String, grupo_sanguineo : String, factor_rh : String,
     direccion : String, observaciones : String, donaciones : Donacion[]) : void
}

class Personal{
    - CI : String
    - nombre : String
    - apellidos : String
    - direccion : String
    - cargo : String

    + Personal(CI : String, nombre : String, apellidos : String, direccion : String, cargo : String) : void
}

class Donacion{
    - fecha : Date
    - volumen : float
    - codigo_bolsa : String
    - localizacion_actual : String
    - CI_empleado : String

    + Donacion(fecha : Date, volumen : float, codigo_bolsa : String,
     localizacion_actual : String, CI_empleado : String) : void
}

BancoDeSangre "1" *-- "*" Donante : Registrado en:
Donante "1" *-- "*" Donacion : Realizado por:
BancoDeSangre "1" *--  "*" Personal : Trabaja en:
@enduml